model_opts:
  name: "Unet"
  args:
    inchannels: 3
    outchannels: 1
    net_depth: 3
    
train_par:
  epochs: 50
  batch_size: 8
  workers: 4
  lr: 0.001
  eval_threshold: 0.5
  patience: 15
  early_stopping_flag: True
  results_path: "results/128x128"
  optimizer:
    name: 'SGD'
  loss_opts:
    name: 'BCELogitsLoss'
    args:
      weight: False # this is for BCELogits & BCEDiceLoss
      alpha: 0.25 # this is only for focal loss
      gamma: 2 # this is only for focal loss

dataset:
  experiment: "exp_001"
  data_dir: "../dataset/128x128"
  train: "data/experiment_001/train_00_cv_00.csv"
  dev: "data/experiment_001/dev_00_cv_00.csv"
  test: "data/experiment_001/test_00.csv"
  normalization: "macenko"
  cache_data: True
  rescale_factor: 128