model_opts:
  name: "Unet"
  args:
    inchannels: 3
    outchannels: 1
    net_depth: 3
    
train_par:
  epochs: 2
  batch_size: 8
  workers: 4
  lr: 0.001
  eval_threshold: 0.5

dataset:
  data_dir: "../dataset/128x128"
  train: "data/experiment_001/train_00_cv_00.csv"
  dev: "data/experiment_001/dev_00_cv_00.csv"
  test: "data/experiment_001/test_00.csv"
  normalization: "macenko"
  cache_data: True